### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by simonneutert** [simonneutert/fridgy#4]
- [x] läuft in Docker, ENV Variablen werden jedoch nicht übernommen

---

In unserem Production Setup, mit Nutzung von [RaspAp](https://github.com/billz/raspap-webgui), ist der Endpoint des API-Servers: 'http://10.3.141.1:8081/'

Dateien für Docker:

- `config/prod.env.js`
- `docker-compose*.yml`
- `Dockerfiles unter docker/*`

Ziel ist es über die docker-compose eine ENV Variable zu setzen, dynamisch den Endpoint zu setzen.

```javascript
// config/prod.env.js

var backendApi = process.env.BACKEND_API || '"http://raspberrypi:8081/"'

module.exports = {
  NODE_ENV: '"production"',
  BACKEND_API: backendApi
}
```

```
version: '2'
services:

  web:
    build:
      context: .
      dockerfile: ./docker/arm/node-frontend/Dockerfile
    environment:
      TZ: 'Europe/Berlin'
      BACKEND_API: 'http://10.3.141.1:8081/'
    ports:
      - "8080:8080"
    links:
      - api_backend:api_backend
    privileged: true
    networks:
      - backend

  api_backend:
    build: 
      context: .
      dockerfile: ./docker/arm/node-backend/Dockerfile
    ports:
     - "8081:8081"
    networks:
      - backend

networks:
  backend:
```
